apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace:  {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: netint
  template:
    metadata:
      labels:
        app: netint
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: netint
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /bin/sh
            - -c
            - "while true; do sleep 30; done"
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
              netint.ca/Quadra: {{ .Values.resources.requests.netint }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
              netint.ca/Quadra: {{ .Values.resources.limits.netint }}
          volumeMounts:
            - name: volume
              mountPath: {{ .Values.volumeMount.mountPath }}
      volumes:
        - name: volume
          hostPath:
            type: Directory
            path: {{ .Values.volumes.hostPath }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
