apiVersion: v1
kind: Pod
metadata:
  name: netint-pod
  namespace: kube-system
  labels:
    name: netint-pod
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: netint-pod
    image: netint/quadra_ubuntu-24.04_ffmpeg:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    securityContext:
      privileged: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
        netint.ca/ASIC: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        netint.ca/ASIC: 1
      requests:
        memory: "128Mi"
        cpu: "500m"
        netint.ca/Quadra: 1
      limits:
        memory: "128Mi"
        cpu: "500m"
        netint.ca/Quadra: 1
    ports:
      - containerPort: 80
  nodeSelector:
    kubernetes.io/hostname: yhtest
